[package]
name = "bitcoin_handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
tokio-native-tls = "0.3.1"
native-tls = "0.2.12"
bitcoin_hashes = "0.14.0"